{basic_settings: {stocks: ["IBM", "AAPL", "SPY", "MSFT", "NVDA"], data_base_name: prices},
dir_paths: {data: data, reports: reports, sql: sql},
sql_files: {create_indicators: create_indicators_table.sql, create_strategy: create_strategy_signals_table.sql}}
